# Generated by Django 5.1.7 on 2025-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('aceito', 'Aceito'), ('em_atendimento', 'Em Atendimento'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20),
        ),
    ]
